MODELS_PATH: "."
EXPS_PATH: "."

HFLICKR_PATH: "./HFlickr"
HDAY2NIGHT_PATH: "./Hday2night"
HCOCO_PATH: "./HCOCO"
HADOBE5K_PATH: "./HAdobe5k"

IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18_SMALL: "./pretrained_models/hrnet_w18_small_model_v2.pth"
  HRNETV2_W18: "./hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"